FROM eclipse-temurin:21-jdk-alpine 
WORKDIR /app
COPY target/react-application-spring-0.0.1-SNAPSHOT.jar react-application-spring-0.0.1-SNAPSHOT.jar
EXPOSE 8080
CMD ["java","-jar","react-application-spring-0.0.1-SNAPSHOT.jar"]
